# compare <- function(x, y, log, nx, ny) {
  if (log) {
    x <- log10(x)
    y <- log10(y)
  }
  pe <- cor.test(x, y)
  d <- data.frame(x=x, y=y)
  print(ggplot(d, aes(x=x, y=y)) +geom_point()+theme_bw()
        +xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value)))
}
  
  
  cla <- read.table("/scratch/trcanmed/RNASeq_biod_metadata/local/share/data/stromal_contamination.txt", sep="\t", header=T)
ma_fpkm <- read.table(gzip("fpkm_lymphoma_scores.tsv.gz"), sep="\t", header=T)
ma_fpkm <- read.table(gzFile("fpkm_lymphoma_scores.tsv.gz"), sep="\t", header=T)
ma_fpkm <- read.table(gzfile("fpkm_lymphoma_scores.tsv.gz"), sep="\t", header=T)
ma_fpkm <- read.table(gzfile("/scratch/trcanmed/DE_RNASeq/dataset/Biodiversa_up5/fpkm_lymphoma_scores.tsv.gz"), sep="\t", header=T)
ma_tmm <- read.table(gzfile("/scratch/trcanmed/DE_RNASeq/dataset/Biodiversa_up5/tmm_lymphoma_scores.tsv.gz"), sep="\t", header=T)
head(cla)
head(ma_tmm)
tmm <- merge(cla, ma_tmm, by.x="X", by.y="row.names")
fpkm <- merge(cla, ma_tmm, by.x="X", by.y="row.names")
head(tmm)
dim(tmm)
dim(fpkm)
dim(cla)
compare <- function(x, y, log) {
if (log) {
x <- log10(x)
y <- log10(y)
}
pe <- cor.test(x, y)
d <- data.frame(x=x, y=y, density=get_density(x,y, n=100))
print(ggplot(d, aes(x=x, y=y, color=density)) +geom_point()+theme_bw()+xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value))+scale_color_viridis_c())
}
library(ggplot2)
compare(tmm$leucos, tmm$Leucocyte)
compare(tmm$leucos, tmm$Leucocyte, FALSE)
compare <- function(x, y, log) {
if (log) {
x <- log10(x)
y <- log10(y)
}
pe <- cor.test(x, y)
d <- data.frame(x=x, y=y)
print(ggplot(d, aes(x=x, y=y, color=density)) +geom_point()+theme_bw()+xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value))+scale_color_viridis_c())
}
compare(tmm$leucos, tmm$Leucocyte, FALSE)
compare(tmm$leucos, tmm$Leucocyte, FALSE, "TMM_Leuco_singleb","TMM_Leuco_together")
if (log) {
x <- log10(x)
y <- log10(y)
}
pe <- cor.test(x, y)
d <- data.frame(x=x, y=y)
print(ggplot(d, aes(x=x, y=y, color=density)) +geom_point()+theme_bw()+xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value))+scale_color_viridis_c())
}
compare <- function(x, y, log, nx, ny) {
if (log) {
x <- log10(x)
y <- log10(y)
}
pe <- cor.test(x, y)
d <- data.frame(x=x, y=y)
print(ggplot(d, aes(x=x, y=y, color=density)) +geom_point()+theme_bw()+xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value))
}
compare <- function(x, y, log, nx, ny) {
if (log) {
x <- log10(x)
y <- log10(y)
}
pe <- cor.test(x, y)
d <- data.frame(x=x, y=y)
print(ggplot(d, aes(x=x, y=y, color=density)) +geom_point()+theme_bw()
+xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value)))
}
compare(tmm$leucos, tmm$Leucocyte, FALSE, "TMM_Leuco_singleb","TMM_Leuco_together")
compare <- function(x, y, log, nx, ny) {
if (log) {
x <- log10(x)
y <- log10(y)
}
pe <- cor.test(x, y)
d <- data.frame(x=x, y=y)
print(ggplot(d, aes(x=x, y=y)) +geom_point()+theme_bw()
+xlab(nx)+ylab(ny)+labs(caption=paste0(pe$estimate, ', pval=', pe$p.value)))
}
compare(tmm$leucos, tmm$Leucocyte, FALSE, "TMM_Leuco_singleb","TMM_Leuco_together")
compare(fpkm$leucos, fpkm$Leucocyte, FALSE, "FPKM_Leuco_singleb","FPKM_Leuco_together")
head(tmm)
head(fpkm)
head(ma_fpkm)
head(ma_tmm)
fpkm <- merge(cla, ma_fpkm, by.x="X", by.y="row.names")
m <- merge(ma_fpkm, ma_tmm, by="row.names")
head(m)
compare(m$Leucocyte.y, m$Leucocyte.x, FALSE, "TMM_Leuco","FPKM_Leuco")
# TODO color by batch
compare(fpkm$leucos, fpkm$Leucocyte, FALSE, "FPKM_Leuco_singleb","FPKM_Leuco_together")
compare(tmm$leucos, tmm$Leucocyte, FALSE, "TMM_Leuco_singleb","TMM_Leuco_together")
annot <- read.table(gzfile("/scratch/trcanmed/RNASeq_biod_metadata/dataset/july2020/selected_metadata_annot_final"), sep="\t", header=T)
head(annot)
mm <- merge(m, annot, by.x="Row.names", by.y="sample_id")
head(m)
mm <- merge(m, annot, by.x="Row.names", by.y="sample_id")
head(annot)
mm <- merge(m, annot, by.x="Row.names", by.y="sample_id_R")
dim(m)
dim(mm)
dim(annot)
dim(m)
ggplot(mm, aes(x=Leucocyte.y, y=Leucocyte.x, color=batch)) +geom_point()+theme_bw()
ggplot(mm, aes(x=Leucocyte.y, y=Leucocyte.x, color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mm, aes(x=log(Leucocyte.y), y=log(Leucocyte.x), color=as.factor(batch))) +geom_point()+theme_bw()
head(fpkm)
mfpkm <- merge(fpkm, annot, by.x="X", by.y"sample_id_R")
mfpkm <- merge(fpkm, annot, by.x="X", by.y="sample_id_R")
#ggplot(mfpkm, aes(x=log(Leucocyte.), y=log(Leucocyte.x), color=as.factor(batch))) +geom_point()+theme_bw()
heaD(mfpkm)
head(mfpkm)
#ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=leucos, y=Leucocyte, color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
mtmm <- merge(tmm, annot, by.x="X", by.y="sample_id_R")
ggplot(mtmm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
cor.test(log(leucos), y=log(Leucocyte))
cor.test(log(mtmm#leucos), y=log(mtmm$Leucocyte))
)
\
cor.test(log(mtmm$leucos), y=log(mtmm$Leucocyte))
ggplot(mtmm, aes(x=leucos, y=Leucocyte, color=as.factor(batch))) +geom_point()+theme_bw()
cor.test(log(mtmm#leucos), y=log(mtmm$Leucocyte))
cor.test(log(mtmm#leucos), y=log(mtmm$3###|Leucocyte))
cor.test(log(mtmm$eucos), y=log(mtmm$3###|Leucocyte))
cor.test(log(mtmm$eucos), y=log(mtmm$Leucocyte))
cor.test(log(mtmm$leucos), y=log(mtmm$Leucocyte))
cor.test(log(mfpkm$leucos), y=log(mfpkm$Leucocyte))
dim(mfpkm)
head(cla)
head(mfpkm)
head(mtmm)
ggplot(mtmm, aes(x=leucos, y=Leucocyte, color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mtmm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(cags), y=log(CAF), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(cafs), y=log(CAF), color=as.factor(batch))) +geom_point()+theme_bw()
cor.test(mfpkm$cafs, mfpkm$CAF)
cor.test(mfpkm$endos, mfpkm$Endothelial)
ggplot(mfpkm, aes(x=log(enods), y=log(Endothelial), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(endos), y=log(Endothelial), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mtmm, aes(x=log(endos), y=log(Endothelial), color=as.factor(batch))) +geom_point()+theme_bw()
head(mtmm)
head(mfpkm)
ggplot(mtmm, aes(x=log(endos), y=log(Endothelial), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(endos), y=log(Endothelial), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(endos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
m4 <- mfpkm[mfpkm$batch=="4",]
ggplot(m4, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(m4, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(type))) +geom_point()+theme_bw()
#ggplot(m4, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(m4, aes(x=log(cafs), y=log(CAF), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(cafs), y=log(CAF), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mtmmm, aes(x=log(cafs), y=log(CAF), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mtmm, aes(x=log(cafs), y=log(CAF), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mtmm, aes(x=log(cafs), y=log(CAF), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mtmm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(type))) +geom_point()+theme_bw()
ggplot(mtmm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
ggplot(mfpkm, aes(x=log(leucos), y=log(Leucocyte), color=as.factor(batch))) +geom_point()+theme_bw()
